FROM node:14-alpine AS build-stage

WORKDIR /usr/src/app

COPY example-frontend .

ENV REACT_APP_BACKEND_URL=http://localhost:8080

RUN npm install && npm run build


FROM node:14-alpine

EXPOSE 5000

WORKDIR /usr/src/app

COPY --from=build-stage /usr/src/app/build ./build

RUN npm install -g serve && npm cache clean --force

CMD ["serve", "-s", "-l", "5000", "build"]
