services:
  frontend:
    container_name: frontend
    image: frontend

  backend:
    container_name: backend
    image: backend
    environment:
      - REDIS_HOST=redis-cache
      - POSTGRES_HOST=postgres

  redis:
    container_name: redis-cache
    image: redis
    ports:
      - 6379:6379

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database:/var/lib/postgresql/data

  reverse-proxy:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
