FROM amazoncorretto:17-alpine AS build

WORKDIR /usr/src/app

COPY spring-example-project .

RUN ./mvnw package


FROM alpine:latest

RUN apk --no-cache add openjdk17-jre

WORKDIR /usr/src/app

RUN adduser -D appuser

USER appuser

EXPOSE 8080

COPY --from=build /usr/src/app/target/docker-example-1.1.3.jar ./docker-example-1.1.3.jar

CMD ["java", "-jar", "./docker-example-1.1.3.jar"]
